# Generated by Django 3.2.6 on 2021-08-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='compete',
            new_name='complete',
        ),
    ]
