# Generated by Django 3.2.3 on 2021-06-29 15:10

import ModelForms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelForms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=20, validators=[ModelForms.validators.title_validator]),
        ),
    ]
