# Generated by Django 3.2.3 on 2021-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_101', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='27', max_length=30),
            preserve_default=False,
        ),
    ]
