# Generated by Django 3.2.3 on 2021-06-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_exercise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='headline',
            new_name='title',
        ),
    ]
